- name: check for java
  stat: path=/usr/bin/java follow=yes
  register: java
- name: check for curl
  apt: name=curl state=present
  when: "not java.stat.exists"
- name: download java
  command: "curl -L -O -H \"Cookie: oraclelicense=accept-securebackup-cookie\" -k \"http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.tar.gz\""
  args:
    creates: jre-8u60-linux-x64.tar.gz
  when: "not java.stat.exists"
- name: extract java
  command: tar -xvzf jre-8u60-linux-x64.tar.gz
  args:
    creates: jre1.8.0_60
  when: "not java.stat.exists"
- name: move java
  command: mv jre1.8.0_60/ /usr/lib/jvm/
  args:
    creates: /usr/lib/jvm
  when: "not java.stat.exists"
- name: update alternatives
  command: 'update-alternatives --install /usr/bin/java "java" /usr/lib/jvm/bin/java "1"'
  args:
    creates: /usr/bin/java
  when: "not java.stat.exists"
- name: add elasticsearch key
  apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
- name: add elasticsearch repository
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/1.5/debian stable main" state=present update_cache=yes
- name: install logstash
  apt: name=logstash state=present
- name: enable logstash
  service: name=logstash enabled=yes
