nodes:
  inboundaggregator:
    config:
      infilters:
        - name: accept inbound IPv4
          conditions:
            - type == 'IPv4'
            - direction == 'inbound'
          actions:
            - accept
        - name: drop all
          actions:
            - drop
    class: AggregatorIPv4
    output: true
    inputs:
      - spamhaus_DROP
      - spamhaus_EDROP
      - dshield_blocklist
  outboundaggregator:
    config:
      infilters:
        - name: accept outbound IPv4
          conditions:
            - type == 'IPv4'
            - direction == 'outbound'
          actions:
            - accept
        - name: drop all
          actions:
            - drop
    class: AggregatorIPv4
    output: true
    inputs:
      - zeustracker_badips
  inboundfeed:
    config: {}
    class: RedisSet
    inputs:
      - inboundaggregator
    output: false
  outboundfeed:
    config: {}
    class: RedisSet
    inputs:
      - outboundaggregator
    output: false
  dshield_blocklist:
    config:
      interval: 600
    class: DshieldBlockList
    output: true
  zeustracker_badips:
    config:
      source_name: https://zeustracker.abuse.ch/blocklist.php?download=badips
      attributes:
        type: IPv4
        direction: outbound
      cchar: "#"
      url: https://zeustracker.abuse.ch/blocklist.php?download=badips
    class: HTTP
    output: true
  spamhaus_DROP:
    config:
      source_name: http://www.spamhaus.org/drop/drop.txt
      attributes:
        type: IPv4
        direction: inbound
      cchar: ;
      split_char: ;
      url: http://www.spamhaus.org/drop/drop.txt
    class: HTTP
    output: true
  spamhaus_EDROP:
    config:
      source_name: http://www.spamhaus.org/drop/edrop.txt
      attributes:
        type: IPv4
        direction: inbound
      cchar: ;
      split_char: ;
      url: http://www.spamhaus.org/drop/edrop.txt
    class: HTTP
    output: true
