- name: minemeld playbook
  hosts: 127.0.0.1
  connection: local
  sudo: yes

  roles:
  - infrastructure
  - { role: minemeld_devel, when: "i == 'devel'" }
  - { role: minemeld, when: "i != 'devel'" }
