- name: minemeld playbook
  hosts: 127.0.0.1
  connection: local
  sudo: yes

  vars:
    main_directory: "/opt/minemeld"
    local_directory: "{{main_directory}}/local"
    db_directory: "{{local_directory}}/data"
    config_directory: "{{local_directory}}/config"
    engine_directory: "{{main_directory}}/engine"
    www_directory: "{{main_directory}}/www"
    venv_directory: "{{main_directory}}/engine/current"
    supervisor_directory: "{{local_directory}}/supervisor"
    prototypes_local_directory: "{{local_directory}}/prototypes"
    prototypes_repo_directory: "{{main_directory}}/prototypes"

  pre_tasks:
  - name: current primary group
    command: id -gn
    sudo: no
    register: my_group
  - name: show current group
    debug: msg="current group {{my_group.stdout}}"
  - name: minemeld user
    user:
      name: minemeld
      group: "{{my_group.stdout}}"
      home: "{{data_directory}}"
      createhome: no
      shell: "/usr/sbin/nologin"
  - name: main directory
    file: state=directory path="{{main_directory}}" owner=minemeld group="{{my_group.stdout}}" mode=0775
  - name: local directory
    file: state=directory path="{{local_directory}}" owner=minemeld group="{{my_group.stdout}}" mode=0775
  - name: db directory
    file: state=directory path="{{db_directory}}" owner=minemeld group="{{my_group.stdout}}" mode=0775
  - name: config directory
    file: state=directory path="{{config_directory}}" owner=minemeld group="{{my_group.stdout}}" mode=0775
  - name: prototypes local directory
    file: state=directory path="{{ prototypes_local_directory }}" owner=minemeld group="{{my_group.stdout}}" mode=0775
  - name: supervisor config directory
    file: state=directory path="{{ supervisor_directory }}/config/conf.d" owner=minemeld group="{{my_group.stdout}}" mode=0775
  - name: supervisor run directory
    file: state=directory path="{{ supervisor_directory }}/run" owner=minemeld group="{{my_group.stdout}}" mode=0775
  - name: update apt
    apt: update_cache=yes

  roles:
  - rabbitmq
  - redis
  - logstash
  - rsyslog
  - minemeld

  post_tasks:
  - name: start nginx
    service: name=nginx state=started
  - name: start supervisor
    service: name=supervisor state=started
  - name: start collectd
    service: name=collectd state=started
  - name: start minemeld-core
    supervisorctl: name=minemeld-core state=started
  - name: start minemeld-web
    supervisorctl: name=minemeld-web state=started
