- name: minemeld playbook
  hosts: 127.0.0.1
  connection: local
  sudo: yes

  vars:
    main_directory: "/opt/minemeld"
    data_directory: "{{main_directory}}/data"
    config_directory: "{{main_directory}}/config"
    repo_directory: "{{main_directory}}/minemeld-core"
    www_directory: "{{main_directory}}/www"
    venv_directory: "{{main_directory}}/mm-venv"

  pre_tasks:
  - name: current primary group
    command: id -gn
    sudo: no
    register: my_group
  - name: show current group
    debug: msg="current group {{my_group.stdout}}"
  - name: minemeld user
    user:
      name: minemeld
      group: "{{my_group.stdout}}"
      home: "{{data_directory}}"
      createhome: no
      shell: "/usr/sbin/nologin"
  - name: main directory
    file: state=directory path="{{main_directory}}" owner=minemeld group="{{my_group.stdout}}" mode=0775
  - name: data directory
    file: state=directory path="{{data_directory}}" owner=minemeld group="{{my_group.stdout}}" mode=0775
  - name: config directory
    file: state=directory path="{{config_directory}}" owner=minemeld group="{{my_group.stdout}}" mode=0775
  - name: update apt
    apt: update_cache: yes

  roles:
  - minemeld

  post_tasks:
  - name: start rabbitmq-server
    service: name=rabbitmq-server state=started
  - name: start redis-server
    service: name=redis-server state=started
  - name: start nginx
    service: name=nginx state=started
  - name: start supervisor
    service: name=supervisor state=started
  - name: start collectd
    service: name=collectd state=started
  - name: start minemeld-core
    supervisorctl: name=minemeld-core state=started
  - name: start minemeld-web
    supervisorctl: name=minemeld-web state=started
