- name: minemeld playbook
  hosts: 127.0.0.1
  connection: local
  sudo: yes

  vars:
    main_directory: "/opt/minemeld"
    data_directory: "{{main_directory}}/data"
    config_directory: "{{main_directory}}/config"
    repo_directory: "{{main_directory}}/minemeld-core"
    www_directory: "{{main_directory}}/www"
    venv_directory: "{{main_directory}}/mm-venv"

  pre_tasks:
  - name: minemeld group
    group: name=minemeld state=present
  - name: current user
    command: whoami
    sudo: no
    register: my_user
  - name: show current user
    debug: msg="current user: {{my_user}}"
  - name: add my_user to group
    user: name={{my_user}} group=minemeld
  - name: minemeld user
    user:
      name: minemeld
      group: minemeld
      home: "{{data_directory}}"
      createhome: no
      shell: "/usr/sbin/nologin"
  - name: main directory
    file: state=directory path="{{main_directory}}" owner=minemeld group=minemeld
  - name: data directory
    file: state=directory path="{{data_directory}}" owner=minemeld group=minemeld
  - name: config directory
    file: state=directory path="{{config_directory}}" owner=minemeld group=minemeld

  roles:
  - minemeld

  post_tasks:
  - name: start rabbitmq-server
    service: name=rabbitmq-server state=started
  - name: start redis-server
    service: name=redis-server state=started
  - name: start nginx
    service: name=nginx state=started
  - name: start supervisor
    service: name=supervisor state=started
  - name: start minemeld-core
    supervisorctl: name=minemeld-core state=started
  - name: start minemeld-web
    supervisorctl: name=minemeld-web state=started
