- name: stop minemeld-core
  supervisorctl: name=minemeld-core state=stopped
- name: stop minemeld-web
  supervisorctl: name=minemeld-web state=stopped
- name: cleanup git repo
  command: git clean -f -d
  args:
    chdir: {{ repo_directory }}
- name: start minemeld-core
  supervisorctl: name=minemeld-core state=started
- name: start minemeld-web
  supervisorctl: name=minemeld-web state=started
- name: restart supervisor
  service: name=supervisor state=restarted
  ignore_errors: yes
- name: restart nginx
  service: name=nginx state=restarted
- name: supervisor insserv config
  command: /usr/lib/insserv/insserv -o supervisor
- name: restart minemeld-core
  supervisorctl: name=minemeld-core state=restarted
- name: restart minemeld-web
  supervisorctl: name=minemeld-web state=restarted
- name: restart collectd
  service: name=collectd state=restarted

