- name: restart supervisor
  service: name=supervisor state=restarted
  ignore_errors: yes
- name: restart nginx
  service: name=nginx state=restarted
- name: supervisor insserv config
  command: /usr/lib/insserv/insserv -o supervisor
- name: restart minemeld-core
  supervisorctl: name=minemeld-core state=restarted
- name: restart minemeld-web
  supervisorctl: name=minemeld-web state=restarted
