- name: install minemeld-core
  command: "{{ venv_directory }}/bin/python setup.py develop"
  args:
    chdir: "{{ core_directory }}"
  sudo: no
- name: supervisor insserv config
  command: /usr/lib/insserv/insserv -o supervisor
- name: restart collectd
  service: name=collectd state=restarted
- name: stop rabbitmq-server
  service: name=rabbitmq-server state=stopped
- name: stop minemeld-core
  supervisorctl: name=minemeld-core state=stopped
- name: stop minemeld-web
  supervisorctl: name=minemeld-web state=stopped
- name: cleanup git repo
  command: git clean -f -d
  args:
    chdir: "{{ core_directory }}"
- name: start rabbitmq-server
  service: name=rabbitmq-server state=started
- name: restart supervisor
  service: name=supervisor state=restarted
  ignore_errors: yes
- name: start minemeld-core
  supervisorctl: name=minemeld-core state=started
- name: start minemeld-web
  supervisorctl: name=minemeld-web state=started
- name: restart nginx
  service: name=nginx state=restarted
- name: restart minemeld-core
  supervisorctl: name=minemeld-core state=restarted
- name: restart minemeld-web
  supervisorctl: name=minemeld-web state=restarted
