- name: git
  apt: name=git state=present
- name: nginx
  apt: name=nginx state=present
- name: rabbitmq-server
  apt: name=rabbitmq-server state=present
- name: g++
  apt: name=g++ state=present
- name: libleveldb-dev
  apt: name=libleveldb-dev state=present
- name: redis-server
  apt: name=redis-server state=present
- name: supervisor
  apt: name=supervisor state=present
- name: minemeld-core repo
  git: 
    repo: https://github.com/PaloAltoNetworks-BD/minemeld-core.git
    clone: yes
    dest: "{{repo_directory}}"
    version: develop
  sudo: no
  notify: 
    - restart minemeld-core
    - restart minemeld-web
- name: repo permissions
  file: path="{{repo_directory}}" state=directory recurse=yes owner=minemeld group=minemeld
- name: virtualenv
  pip: name=virtualenv
- name: minemeld virtualenv
  command: virtualenv "{{venv_directory}}" -p python2.7 creates="{{venv_directory}}"
- name: virtualenv permissions
  file: path="{{venv_directory}}" state=directory recurse=yes owner=minemeld group=minemeld
- name: requirements
  pip:
    virtualenv: "{{venv_directory}}"
    requirements: "{{repo_directory}}/requirements.txt"
- name: requirements web
  pip:
    virtualenv: "{{venv_directory}}"
    requirements: "{{repo_directory}}/requirements-web.txt"
- name: minemeld-core config
  copy:
    force: no
    dest: "{{config_directory}}/running-config.yml"
    src: running-config.yml
    owner: minemeld
    group: minemeld
    mode: 0644
- name: minemeld-web config
  copy:
    force: no
    dest: "{{config_directory}}/wsgi.yml"
    src: wsgi.yml
    owner: minemeld
    group: minemeld
    mode: 0644
- name: supervisor minemeld-core program
  template:
    src: minemeld-core.supervisord.j2
    dest: "/etc/supervisor/conf.d/minemeld-core.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart supervisor
- name: supervisor minemeld-web program
  template:
    src: minemeld-web.supervisord.j2
    dest: "/etc/supervisor/conf.d/minemeld-web.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart supervisor
- name: nginx config
  template:
    src: minemeld-web.nginx.j2
    dest: /etc/nginx/sites-enabled/minemeld-web
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
- name: supervisor insserv config
  template:
    src: supervisor.insserv.j2
    dest: /etc/insserv/overrides/supervisor
    owner: root
    group: root
    mode: 0644
  notify: supervisor insserv config

