- name: install packages
  apt: name={{item}} state=present
  with_items:
    - git
    - nginx
    - g++
    - libleveldb-dev
    - supervisor
    - collectd-core
    - librrd-dev
    - libxslt1-dev
- name: download rsyslog minemeld modules
  get_url: url=https://paloaltonetworks.box.com/shared/static/1at3pq1mrlg8hfabm1p0c7mpo4fofoxu.deb dest=/tmp/rsyslog-minemeld_8.14-0.deb
- name: install rsyslog minemeld module
  apt: deb=/tmp/rsyslog-minemeld_8.14-0.deb state=present
- name: minemeld-node-prototypes repo
  git:
    repo: https://github.com/PaloAltoNetworks-BD/minemeld-node-prototypes.git
    clone: yes
    dest: "{{prototypes_repo_directory}}"
    version: develop
  sudo: no
- name: minemeld-core repo
  git: 
    repo: https://github.com/PaloAltoNetworks-BD/minemeld-core.git
    clone: yes
    dest: "{{core_directory}}"
    version: develop
  sudo: no
  notify:
    - install minemeld-core
    - stop rabbitmq-server
    - stop minemeld-core
    - stop minemeld-web
    - cleanup git repo
    - start rabbitmq-server
    - start minemeld-core
    - start minemeld-web
  when: core
- name: minemeld-gui repo
  git:
    repo: https://github.com/PaloAltoNetworks-BD/minemeld-gui.git
    clone: yes
    dest: "{{www_directory}}"
    version: master
  sudo: no
  when: gui

- name: core permissions
  file: path="{{core_directory}}" state=directory recurse=yes owner=minemeld group="{{my_group.stdout}}" mode=u=rwX,g=rwX,o=rX
- name: www permissions
  file: path="{{www_directory}}" state=directory recurse=yes owner=minemeld group="{{my_group.stdout}}" mode=u=rwX,g=rwX,o=rX

- name: virtualenv
  pip: name=virtualenv
- name: minemeld virtualenv
  command: virtualenv "{{venv_directory}}" -p python2.7 creates="{{venv_directory}}"
- name: virtualenv permissions
  file: path="{{venv_directory}}" state=directory recurse=yes owner=minemeld group="{{my_group.stdout}}" mode=u=rwX,g=rwX,o=rX

- name: requirements
  pip:
    virtualenv: "{{venv_directory}}"
    requirements: "{{core_directory}}/requirements.txt"
  sudo: no
- name: requirements web
  pip:
    virtualenv: "{{venv_directory}}"
    requirements: "{{core_directory}}/requirements-web.txt"
  sudo: no
- name: requirements dev
  pip:
    virtualenv: "{{venv_directory}}"
    requirements: "{{core_directory}}/requirements-dev.txt"
  sudo: no

- name: minemeld-core config
  copy:
    force: no
    dest: "{{config_directory}}/running-config.yml"
    src: running-config.yml
    owner: minemeld
    group: "{{my_group.stdout}}"
    mode: 0644
- name: minemeld-web config
  copy:
    force: no
    dest: "{{config_directory}}/wsgi.yml"
    src: wsgi.yml
    owner: minemeld
    group: "{{my_group.stdout}}"
    mode: 0644
- name: minemeld-web users
  copy:
    force: no
    dest: /etc/nginx/minemeld.htpasswd
    src: minemeld.htpasswd
    group: www-data
    mode: 0640
  notify: restart nginx
- name: supervisor minemeld-core program
  template:
    src: minemeld-core.supervisord.j2
    dest: "/etc/supervisor/conf.d/minemeld-core.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart supervisor
- name: supervisor minemeld-web program
  template:
    src: minemeld-web.supervisord.j2
    dest: "/etc/supervisor/conf.d/minemeld-web.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart supervisor
- name: nginx certificate
  copy:
    force: no
    dest: /etc/nginx/minemeld.cer
    src: minemeld.cer
    mode: 0644
  notify: restart nginx
- name: nginx private key
  copy:
    force: no
    dest: /etc/nginx/minemeld.pem
    src: minemeld.pem
    mode: 0600
  notify: restart nginx
- name: nginx config
  template:
    src: minemeld-web.nginx.j2
    dest: /etc/nginx/sites-enabled/minemeld-web
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
- name: delete nginx default
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
- name: supervisor insserv config
  template:
    src: supervisor.insserv.j2
    dest: /etc/insserv/overrides/supervisor
    owner: root
    group: root
    mode: 0644
  notify: supervisor insserv config
- name: collectd config
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart collectd
- name: collectd types
  template:
    src: minemeld_types.db.j2
    dest: /etc/collectd/minemeld_types.db
    owner: root
    group: root
    mode: 0644
  notify: restart collectd
