- name: create minemeld group
  group: name=minemeld state=present
- name: current user
  command: id -gn
  sudo: no
  register: my_user
- name: show current user
  debug: msg="current user {{my_user.stdout}}"
- name: add current user to minemeld group
  user: name="{{my_user.stdout}}" groups=minemeld append=yes
- name: minemeld user
  user:
    name: minemeld
    group: "minemeld"
    home: "{{db_directory}}"
    createhome: no
    shell: "/usr/sbin/nologin"
- name: main directory
  file: state=directory path="{{main_directory}}" owner=minemeld group="minemeld" mode=0775
- name: local directory
  file: state=directory path="{{local_directory}}" owner=minemeld group="minemeld" mode=0775
- name: db directory
  file: state=directory path="{{db_directory}}" owner=minemeld group="minemeld" mode=0775
- name: config directory
  file: state=directory path="{{config_directory}}" owner=minemeld group="minemeld" mode=0775
- name: prototypes local directory
  file: state=directory path="{{ prototypes_local_directory }}" owner=minemeld group="minemeld" mode=0775
- name: supervisor config directory
  file: state=directory path="{{ supervisor_directory }}/config/conf.d" owner=minemeld group="minemeld" mode=0775
- name: supervisor run directory
  file: state=directory path="{{ supervisor_directory }}/run" owner=minemeld group="minemeld" mode=0775
- name: log directory
  file: state=directory path="{{ main_directory }}/log" owner=minemeld group="minemeld" mode=0775
- name: install packages
  apt: name={{item}} state=present
  with_items:
    - git
    - g++
    - libleveldb-dev
    - librrd-dev
    - libxslt1-dev
- name: minemeld-node-prototypes repo
  git:
    repo: https://github.com/PaloAltoNetworks/minemeld-node-prototypes.git
    clone: yes
    dest: "{{prototypes_repo_directory}}/minemeld-node-prototypes"
    version: develop
  sudo: no
- name: minemeld-node-prototypes current link
  file:
    src: "{{prototypes_repo_directory}}/minemeld-node-prototypes/prototypes"
    dest: "{{prototypes_repo_directory}}/current"
    state: link
- name: minemeld-core repo
  git: 
    repo: https://github.com/PaloAltoNetworks/minemeld-core.git
    clone: yes
    dest: "{{engine_directory}}/core"
    version: develop
  sudo: no
- name: engine permissions
  file: path="{{engine_directory}}" state=directory recurse=yes owner=minemeld group="minemeld" mode=u=rwX,g=rwX,o=rX
- name: www permissions
  file: path="{{www_directory}}" state=directory recurse=yes owner=minemeld group="minemeld" mode=u=rwX,g=rwX,o=rX

- name: virtualenv
  pip: name=virtualenv
- name: minemeld virtualenv
  command: virtualenv "{{venv_directory}}" -p python2.7 creates="{{venv_directory}}"
- name: virtualenv permissions
  file: path="{{venv_directory}}" state=directory recurse=yes owner=minemeld group="minemeld" mode=u=rwX,g=rwX,o=rX

- name: requirements
  pip:
    virtualenv: "{{venv_directory}}"
    requirements: "{{engine_directory}}/core/requirements.txt"
  sudo: no
- name: requirements web
  pip:
    virtualenv: "{{venv_directory}}"
    requirements: "{{engine_directory}}/core/requirements-web.txt"
  sudo: no
- name: requirements dev
  pip:
    virtualenv: "{{venv_directory}}"
    requirements: "{{engine_directory}}/core/requirements-dev.txt"
  sudo: no

- name: minemeld-engine config
  copy:
    force: no
    dest: "{{config_directory}}/running-config.yml"
    src: running-config.yml
    owner: minemeld
    group: "minemeld"
    mode: 0644
- name: minemeld-web config
  copy:
    force: no
    dest: "{{config_directory}}/wsgi.yml"
    src: wsgi.yml
    owner: minemeld
    group: "minemeld"
    mode: 0644
- name: minemeld-web users
  copy:
    force: no
    dest: "{{config_directory}}/minemeld.htpasswd"
    src: minemeld.htpasswd
    owner: minemeld
    mode: 0640
  notify: restart nginx
- name: supervisor config
  template:
    src: supervisord.conf.j2
    dest: "{{local_directory}}/supervisor/config/supervisord.conf"
    owner: minemeld
    mode: 0644
- name: minemeld init
  template:
    src: supervisor.init.j2
    dest: /etc/init.d/minemeld
    owner: root
    group: root
    mode: 0744
- name: minemeld service
  service:
    name: minemeld
    enabled: yes
- name: supervisor minemeld-engine program
  template:
    src: minemeld-engine.supervisord.j2
    dest: "{{local_directory}}/supervisor/config/conf.d/minemeld-engine.conf"
    owner: root
    group: root
    mode: 0644
- name: supervisor minemeld-web program
  template:
    src: minemeld-web.supervisord.j2
    dest: "{{local_directory}}/supervisor/config/conf.d/minemeld-web.conf"
    owner: root
    group: root
    mode: 0644
- name: nginx certificate
  copy:
    force: no
    dest: /etc/nginx/minemeld.cer
    src: minemeld.cer
    mode: 0644
  notify: restart nginx
- name: nginx private key
  copy:
    force: no
    dest: /etc/nginx/minemeld.pem
    src: minemeld.pem
    mode: 0600
  notify: restart nginx
- name: nginx config
  template:
    src: minemeld-web.nginx.j2
    dest: /etc/nginx/sites-enabled/minemeld-web
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
- name: delete nginx default
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
- name: collectd config
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart collectd
- name: collectd types
  template:
    src: minemeld_types.db.j2
    dest: /etc/collectd/minemeld_types.db
    owner: root
    group: root
    mode: 0644
  notify: restart collectd
